language: node_js
node_js:
- '0.10'
- '0.12'
- '4'
- '5'
before_install: npm install -g npm@'>=2.13.5'
deploy:
  provider: npm
  email: admin@movingimage24.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    repo: MovingImage24/mi-angular-wbc-pack
    node: '4'
