language: node_js
node_js:
- '7'
before_install: npm install -g npm@'>=4.2.0'
deploy:
  provider: npm
  email: admin@movingimage24.com
  api_key:
    secure: $NPM_TOKEN
  on:
    tags: true
    repo: MovingImage24/mi-angular-wbc-pack
    node: '7'
